# Generated by Django 3.0.6 on 2020-05-25 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Ответ')),
                ('is_true', models.BooleanField(db_index=True, default=False, verbose_name='Верный ответ?')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='main.Answer', verbose_name='Выбранный ответ')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Название предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('max_score', models.PositiveIntegerField(default=12, verbose_name='Максимальная оценка теста')),
                ('content', models.TextField(verbose_name='Описание теста')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Тест опубликован?')),
                ('public_at', models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='Дата публикации теста')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='main.Lesson', verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_start', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Тест начат')),
                ('test_end', models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='Тест закончен')),
                ('test_score', models.PositiveIntegerField(blank=True, db_index=True, default=None, verbose_name='Набрано балов')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Exam')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Вопрос')),
                ('score', models.FloatField(default=1.0, verbose_name='Оценка за правильный ответ')),
                ('variant', models.PositiveIntegerField(db_index=True, default=1, verbose_name='№ варианта')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='main.Task', verbose_name='Тест')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='tasks',
            field=models.ManyToManyField(through='main.Test', to='main.Task'),
        ),
        migrations.AddField(
            model_name='exam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='main.Question', verbose_name='Вопрос'),
        ),
    ]
