# Generated by Django 3.0.6 on 2020-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('test', 'content'), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Описание задаваемого вопроса в тесте', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Учитывать вопрос в тесте', verbose_name='Задание учтено'),
        ),
    ]
