# Generated by Django 3.0.6 on 2020-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, help_text='Название класса или группы', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(help_text='Название класса или группы', to='main.Group', verbose_name='Названия'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('content', 'question', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('content', 'test', 'variant', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'lesson', 'content', 'is_active')},
        ),
    ]
