# Generated by Django 3.0.6 on 2020-05-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='main.Answer', verbose_name='Выбранный ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_end',
            field=models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='Тест закончен'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_score',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, verbose_name='Набрано балов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_start',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Тест начат'),
        ),
    ]
