# Generated by Django 3.0.6 on 2020-05-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('name',), 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('name',), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, help_text='Пользовательский аккаунт, который прошел процесс подтверждения', verbose_name='Подтверждение аккаунта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='public_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Дата публикации теста', null=True, verbose_name='Дата публикации'),
        ),
    ]
