# Generated by Django 3.0.6 on 2020-05-31 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200531_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Дата последнего изменения', verbose_name='Дата изснения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Дата последнего изменения', verbose_name='Дата изснения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Дата последнего изменения', verbose_name='Дата изснения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Дата последнего изменения', verbose_name='Дата изснения'),
            preserve_default=False,
        ),
    ]
