# Generated by Django 3.0.6 on 2020-05-28 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200528_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('test', 'content'), 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-public_at',), 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображение и учитывание ответа в вопросе', verbose_name='Статус ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображение и учитывание вопроса в тесте', verbose_name='Статус вопроса'),
        ),
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор теста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.BooleanField(default=False, help_text='Возможность выбора нескольких вариантов ответа', verbose_name='Множественный выбор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Опубликовать тест на сайте', verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='main.Lesson', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='public_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, help_text='Дата публикации теста на сайте', null=True, verbose_name='Дата публикации'),
        ),
    ]
