# Generated by Django 3.0.6 on 2020-06-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200531_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('variant', 'test', 'content'), 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(db_index=True, help_text='Детальное описание теста', verbose_name='Описание теста'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата последнего изменения', verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, help_text='Короткое название теста', max_length=100, verbose_name='Название теста'),
        ),
    ]
