# Generated by Django 3.0.6 on 2020-05-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200528_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Ответил', 'verbose_name_plural': 'Ответили'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Сданный тест', 'verbose_name_plural': 'Сданные тесты'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображение на сайте', verbose_name='Статус предмета'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('lesson', 'author', 'name')},
        ),
    ]
