# Generated by Django 3.0.8 on 2020-07-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200717_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='tasks',
        ),
    ]
