# Generated by Django 3.0.6 on 2020-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200601_0321'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(max_score__gt=0), name='max_score_gt_0'),
        ),
    ]
