# Generated by Django 3.0.6 on 2020-05-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200530_0303'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('name',)},
        ),
    ]
