# Generated by Django 3.0.6 on 2020-05-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200530_0307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'content', 'variant')},
        ),
    ]
