# Generated by Django 3.0.6 on 2020-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200602_1735'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='max_score_gt_0',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(score__gt=0), name='score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(check=models.Q(variant__gte=1), name='variant_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(max_score__gt=0), name='max_score_non_negative'),
        ),
    ]
