# Generated by Django 3.0.8 on 2020-07-23 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exam_date_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='main.Task', verbose_name='Тест'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('user', 'task')},
        ),
        migrations.RemoveField(
            model_name='test',
            name='exam',
        ),
    ]
