# Generated by Django 3.0.6 on 2020-05-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200530_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(db_index=True, help_text='Описание возможного ответа', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Учитывать ответ при отображение вопроса', verbose_name='Отображение ответа'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Опубликовать предмет на сайте', verbose_name='Отображение на сайте'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(db_index=True, help_text='Предмет, знания которого проверяются в тесте', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Учитывать вопрос в теста', verbose_name='Отображение вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.BooleanField(db_index=True, default=False, help_text='Возможность выбора нескольких вариантов ответа', verbose_name='Множественный выбор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(db_index=True, help_text='Детальное описание теста', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Опубликовать тест на сайте', verbose_name='Отображение на сайте'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(db_index=True, help_text='Короткое название теста', max_length=100, verbose_name='Название '),
        ),
    ]
