# Generated by Django 3.0.8 on 2020-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200723_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_score',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Оценка за тест'),
        ),
    ]
