# Generated by Django 3.0.6 on 2020-05-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200530_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_modified', to=settings.AUTH_USER_MODEL, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='last_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions_modified', to=settings.AUTH_USER_MODEL, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='last_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks_modified', to=settings.AUTH_USER_MODEL, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
    ]
