# Generated by Django 3.0.8 on 2020-07-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200724_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type_answer',
            field=models.BooleanField(db_index=True, default=False, help_text='Предоставить пользователю возможность выбора нескольких вариантов ответа', verbose_name='Множественный выбор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_score',
            field=models.PositiveIntegerField(default=12, help_text='Максимальная оценка за все правильные ответы в тесте', verbose_name='Максимальная оценка'),
        ),
    ]
