# Generated by Django 3.0.6 on 2020-05-30 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200530_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='last_modified',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='answers_modified', to=settings.AUTH_USER_MODEL, verbose_name='Последнее изменение'),
            preserve_default=False,
        ),
    ]
