# Generated by Django 3.0.8 on 2020-07-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200725_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-id',), 'verbose_name': 'Сданный тест', 'verbose_name_plural': 'Сданные тесты'},
        ),
    ]
