# Generated by Django 3.0.8 on 2020-07-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200725_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.Test', verbose_name='Тест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='is_end',
            field=models.BooleanField(db_index=True, default=False, help_text='Прохождение теста закончено', verbose_name='Закончен'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Учитывать ответ при отображении вопроса', verbose_name='Ответ учтен'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('test', 'answer')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='user',
        ),
    ]
