# Generated by Django 3.0.8 on 2020-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200726_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('id',), 'verbose_name': 'Ответил', 'verbose_name_plural': 'Ответили'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='date_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа'),
        ),
    ]
