# Generated by Django 3.1 on 2020-08-07 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200802_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата начала ответа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='variant',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Вариант подобранный для прохождения теста', verbose_name='Вариант вопросов'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
